### ISSUE TITLE
Massive logspam on 1.17 version

### ISSUE THREAD

**Issue by Bluberry-Kat** [Draylar/miners-horizon#20]
Hi!  
On Miner's Horizon 1.7.0-1.17.1, this error is written to the log many times per tick upon entering the dimension.  
`Empty height range: [100 above bottom-255 below top]`  
You can see an example of my logs here, at line 333, where I enter the dimension for roughly 10 seconds: [gist link](https://gist.github.com/Birgliss/835c509a8ecfc4df90018778ae31f9bc#file-2021-09-10-6-log-L333)  
Since this is the entirety of my log, there is a modlist at the top (starting at line 10).

I'm not sure if this error is indicative of a greater bug or not, perhaps some ores aren't spawning, I'm not sure.
I didn't feel comfortable looking into it; I have an SSD and am wary about excess write operations.

**Comment by Draylar** [comment]
Fixed thanks to ishland's contributions in the next update!
