### ISSUE TITLE
various problems

### ISSUE THREAD

**Issue by Chuunkyz** [Draylar/miners-horizon#22]
hi, i'd love to add it in my pack but 

logspam
the config seems to do nothing
coal gen seems broken

also pls add copper in the default ores

**Comment by wootaboot** [comment]
All of these issues have been reported already

**Comment by Draylar** [comment]
Thanks to ishland for fixing the log spam, & the next update will add copper ore as a default ore.

![image](https://user-images.githubusercontent.com/17728338/137781692-54959a0d-80fa-4664-b49d-ab6c01e57f9e.png)
