### ISSUE TITLE
MI Ores still not generating with latest release

### ISSUE THREAD

**Issue by dandin87** [Draylar/miners-horizon#24]
I still am not able to get MI ores to generate. Below is my config for All Of Fabric 4. I also testing with only MI and Miners Horizon and still had the same issue. All other modded ores I've added do spawn. I have even had regular blocks from other mods like blockus spawn. But no blocks from MI that I add will generate at all.

[minershorizon.txt](https://github.com/Draylar/miners-horizon/files/7371343/minershorizon.txt)

**Comment by Chuunkyz** [comment]
MI ores aren't the only ores that don't work in the dimension btw
i have the same problem for Dense Ores

**Comment by dandin87** [comment]
Using Loader 0.12.2 and java flag -Dfabric.debug.loadLate=minershorizon  
This makes it work Unfortunately a java flag is not something we can ship with a modpack..

**Comment by Draylar** [comment]
Thanks to Technician for actually fixing the issue this time 😆 - confirmed working in production 1.17.1, out in a second :)

![image](https://user-images.githubusercontent.com/17728338/138615758-b8bd2b01-7e7f-4e38-9859-7ebe61850791.png)

**Comment by Chuunkyz** [comment]
any idea of why the mi ores aren't affected by the dark stone effect ?
